### PR TITLE
Allow setting openOn via html data attribute

### PR DESCRIPTION
**Pull request by huoxito**
I need to be able to do something like `data-tooltip-openOn="hover focus"` for some elements.

Is there a particular reason for not having support for this?

cheers

### CODE REVIEW

**Comment by geekjuice** [comment]
I actually think this would make more sense in the `drop` library. In addition to `openOn`, I don't see a real reason why we can't support most of the `drop` options as data attributes, so if you'd like to start a PR for that in the `drop` library, I'd be more than happy to look it over and help where I can :+1:

**Comment by huoxito** [comment]
true @geekjuice just to make sure I have this right, you're talking about moving the checks on the Tooltip constructor [here](https://github.com/HubSpot/tooltip/blob/0f1ac01a5ecff520dc398e65074edff14d6dab6a/src/js/tooltip.js#L25-L30) to the Drop constructor right?

I'll start with `position` and `openOn` and submit the PR there thanks!

Let me know if you'd like to remove the `position` data attr handling on this PR.

**Comment by geekjuice** [comment]
Awesome. :+1:

**Comment by huoxito** [comment]
updated the commit to now drop the data attributes handling, not sure this is the right time but I'm assuming at some point this will be needed, maybe once there's a version bump in Drop.js, cheers

**Comment by huoxito** [comment]
hi there @geekjuice you think this could still be merged?

Also you guys have any plans for a new tooltip release? Looks like the latest tagged version is locked on tether 1.0 and drop 1.1 which is causing some issues on our app. When using tooltip 1.1.0 we get a bunch of these _TypeError: this.element.parentNode is null_ coming from Tether.

Sorry I can't give more details, having been able to isolate the issue yet. When I manually add dist/tooltip.js from master branch here the issues goes away (and bump tether and drop to latest versions)

**Pull request closed without merging**
