### PR TITLE
Add ARIA attributes

### PR DESCRIPTION
**Pull request by TrevorBurnham**
@thejameskyle Re: #50, this PR adds the `role=tooltip` attribute to the tooltip content element, and the `aria-describedby` attribute to the tooltip target.

Note that these changes require Drop v1.4.2 in order to work, due to the issue described at HubSpot/drop#134.

It would be nice to have `aria-hidden` as well, but that's really a change that should be made to Drop, since it's not Tooltip-specific. I'll take a crack at that later.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Awesome, thank you @TrevorBurnham

**Comment by geekjuice** [comment]
Could we bump to `1.2.0` since these changes are adding more than they are fixing? #nitpick

**Comment by TrevorBurnham** [comment]
Done and done.

**Comment by geekjuice** [comment]
:tada:  :100:

**Comment by TrevorBurnham** [comment]
> It would be nice to have `aria-hidden` as well

On second glance, it looks like this would be redundant with the `display: none` style that tooltips have while hidden, at least ([according to this source](https://www.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/)). Does that make sense to you, @thejameskyle?

**Comment by jamiebuilds** [comment]
They sound like they know what they are talking about far more than I do so I would listen to them.

**Pull request merged**
